services:
  redis:
    image: redis:7-alpine
    container_name: redis
    command: /bin/sh -c "redis-server --requirepass password"
    hostname: redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    restart: unless-stopped


volumes:
  redis_data:
    name: redis_data